version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: online_shop_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    env_file:
      - .env  # Reference the .env file
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: online_shop_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: online_shop
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

